# Generated by Django 2.1.8 on 2019-05-31 14:20

import Submission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='image',
            field=models.ImageField(null=True, upload_to=Submission.models.submission_image_path),
        ),
    ]
