# Generated by Django 2.1.8 on 2019-05-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Submission', '0003_coachings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coachings',
            new_name='Coaching',
        ),
    ]
